# Generated by Django 3.2.5 on 2022-05-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_numreview_product_numreviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='toatalPrice',
            new_name='totalPrice',
        ),
    ]
